#!/bin/sh

sudo apt update
sudo apt upgrade -y
sudo apt -y remove xrdp
sudo apt -y install xfce4 xfce4-goodies dbus-x11 git libnss3 tightvncserver  libgbm-dev libasound2 webcamoid-plugins lsb-release php php-curl sudo xfonts-base libgbm-dev libasound2 webcamoid-plugins lsb-release iptables mc

## Add user
egrep "/home/a" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
    echo "user exists!"
else
    useradd -m -p paVVzfujVTJns a
    [ $? -eq 0 ] && echo "User a has been added to system!" || echo "Failed to add a user!"
    usermod -aG sudo a
fi



make_dirs()
{
    echo "make_dirs"
    mkdir -p /home/a/scripts
    mkdir -p /home/a/Documents/plots
    mkdir -p /home/a/Documents/plots_tmp
    chown a -R /home/a/*
}


download_scripts()
{
    mkdir -p /home/a/scripts
    chown a -R /home/a/*
}

make_firewall()
{
#    echo "make_firewall"
    ## Файервол
sudo iptables-restore << EOF
# Generated by xtables-save v1.8.2 on Tue May  4 04:40:36 2021
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:allow-vnc - [0:0]
-A INPUT -p tcp -m multiport --dports 5901,5902 -j allow-vnc
-A allow-vnc -s 91.225.152.187/32 -j ACCEPT
-A allow-vnc -s 95.158.53.0/24 -j ACCEPT
-A allow-vnc -s 176.31.182.101/32 -j ACCEPT
-A allow-vnc -s 88.198.7.113/32 -j ACCEPT
-A allow-vnc -j DROP
COMMIT
EOF


#    echo "\n" | sudo apt -y install iptables-persistent
}

install_vnc()
{
    echo "install_vnc"
## Установка vnc
mkdir -p /home/a/.vnc
chown a:a /home/a/.vnc
sudo rm -f /home/a/.vnc/*
sudo cat > /home/a/.vnc/xstartup << EOF
#!/bin/sh
xrdb $HOME/.Xresources
startxfce4 &
EOF

    sudo chmod +x /home/a/.vnc/xstartup

    #sudo -u a vncpasswd
    echo bb9QfSEbDOI= | base64 -d > /home/a/.vnc/passwd
    chown a:a /home/a/.vnc/passwd
    chmod 600 /home/a/.vnc/passwd

    sudo killall Xtightvnc

    cat > /etc/systemd/system/vncserver@.service << EOF
[Unit]
Description=Start TightVNC server at startup
After=syslog.target network.target

[Service]
Type=forking
User=a
Group=a
WorkingDirectory=/home/a

PIDFile=/home/a/.vnc/%H:%i.pid
ExecStartPre=-/usr/bin/vncserver -kill :%i > /dev/null 2>&1
ExecStart=/usr/bin/vncserver -depth 24 -geometry 1280x800 :%i
ExecStop=/usr/bin/vncserver -kill :%i

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable vncserver@1.service
    sudo systemctl start vncserver@1
}

install_chia()
{
    echo "install_chia"
    su a <<'EOF'
    ## Install chia
    cd /home/a

    # Checkout the source and install
    git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules
    cd chia-blockchain

    sh install.sh

    . ./activate

    # The GUI requires you have Ubuntu Desktop or a similar windowing system installed.
    # You can not install and run the GUI as root

    sh install-gui.sh
    deactivate
EOF

    ## скрипт запуска chia, через оболочку xfce сделать автостарт
    sudo cat > /home/a/chia_start.sh << EOF
#!/usr/bin/env bash
set -e
cd ~/chia-blockchain
source venv/bin/activate
cd chia-blockchain-gui
npm run electron
deactivate
EOF

    sudo chmod +x /home/a/chia_start.sh

    sudo chown root:root /home/a/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/chrome-sandbox
    sudo chmod 4755 /home/a/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/chrome-sandbox
}

make_dirs
make_firewall
install_vnc
install_chia
