#!/bin/sh

sudo apt update
sudo apt upgrade -y
sudo apt -y install php php-curl sudo git lsb-release

sudo apt -y install iptables
## Файервол
sudo cat | iptables-restore << EOF
# Generated by xtables-save v1.8.2 on Tue May  4 04:40:36 2021
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:allow-vnc - [0:0]
-A INPUT -p tcp -m multiport --dports 5901,5902 -j allow-vnc
-A allow-vnc -s 91.225.152.187/32 -j ACCEPT
-A allow-vnc -s 95.158.53.0/24 -j ACCEPT
-A allow-vnc -s 176.31.182.101/32 -j ACCEPT
-A allow-vnc -s 88.198.7.113/32 -j ACCEPT
-A allow-vnc -j DROP
COMMIT
EOF

sudo apt -y remove xrdp
sudo apt -y install iptables-persistent mc xfce4 xfce4-goodies dbus-x11

## add user
egrep "/home/a" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
    echo "user exists!"
else
    useradd -m -p paVVzfujVTJns p
    [ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
    usermod -aG sudo a
fi

## Установка vnc
mkdir -p /home/a/.vnc
sudo rm -f /home/a/.vnc/*
sudo cat > /home/a/.vnc/xstartup << EOF
#!/bin/sh
xrdb $HOME/.Xresources
startxfce4 &
EOF

sudo chmod +x /home/a/.vnc/xstartup

sudo -u a vncpasswd

sudo killall Xtightvnc

cat > /etc/systemd/system/vncserver@.service << EOF
[Unit]
Description=Start TightVNC server at startup
After=syslog.target network.target

[Service]
Type=forking
User=a
Group=a
WorkingDirectory=/home/a

PIDFile=/home/a/.vnc/%H:%i.pid
ExecStartPre=-/usr/bin/vncserver -kill :%i > /dev/null 2>&1
ExecStart=/usr/bin/vncserver -depth 24 -geometry 1280x800 :%i
ExecStop=/usr/bin/vncserver -kill :%i

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable vncserver@1.service
sudo systemctl start vncserver@1

## скрипт запуска chia, через оболочку xfce сделать автостарт
sudo cat > /home/a/chia_start.sh << EOF
#!/usr/bin/env bash
set -e
cd ~/chia-blockchain
source venv/bin/activate
cd chia-blockchain-gui
npm run electron
deactivate
EOF

sudo chmod +x /home/a/chia_start.sh


## Install chia


sudo chown root:root /home/a/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/chrome-sandbox
sudo chmod 4755 /home/a/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/chrome-sandbox


function make_dirs() {
    mkdir -p /home/a/scripts
    mkdir -p /home/a/Documents/plots
    mkdir -p /home/a/Documents/plots_tmp
}


function download_scripts() {
    mkdir -p /home/a/scripts
}


